import React, { useEffect, useState } from 'react';
import axios from 'axios';
import Movie from './movie';

const Movies = () => {

  const [movies, setMovies] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);

    setLoading(false);
    setMovies(
      [
        { "backdrop_path": "/iSA7iVTzExSuXvjDEoFELwY5JgT.jpg", "first_air_date": "2019-07-09", "genre_ids": [10764], "id": 90521, "name": "Love Island", "origin_country": ["US"], "original_language": "en", "original_name": "Love Island", "overview": "American version of the British dating reality competition in which ten singles come to stay in a villa for a few weeks and have to couple up with one another. Over the course of those weeks, they face the public vote and might be eliminated from the show. Other islanders join and try to break up the couples.", "popularity": 1875.092, "poster_path": "/47X1h91UUfhMxO42KV9fKoGAVMC.jpg", "vote_average": 7.3, "vote_count": 41 },
        { "backdrop_path": "/hLySjP3yy115dtSUTT3p7sn76oh.jpg", "first_air_date": "2019-05-27", "genre_ids": [10764], "id": 90522, "name": "Love Island", "origin_country": ["BE", "NL"], "original_language": "nl", "original_name": "Love Island", "overview": "The Dutch/Flemish version of Love Island will see a stunning cast engage in the ultimate game of love, as they land in a sunshine paradise in search of passion and romance. Each of the glamorous contestants will live like celebrities in a luxury villa, but in order to stay there they will not only have to win over the hearts of each other, but also the hearts of the viewers. Can true love win out on Love Island or is it all a game?", "popularity": 1762.932, "poster_path": "/46gYkk7qMmmacyrYRPesonseQqx.jpg", "vote_average": 4.8, "vote_count": 4 },
        { "backdrop_path": "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg", "first_air_date": "2016-07-15", "genre_ids": [18, 10765, 9648], "id": 66732, "name": "Stranger Things", "origin_country": ["US"], "original_language": "en", "original_name": "Stranger Things", "overview": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.", "popularity": 1589.254, "poster_path": "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", "vote_average": 8.6, "vote_count": 12849 },
        { "backdrop_path": "/sIRK4NYe1OK2hOJAg4xxuxzceKk.jpg", "first_air_date": "2022-05-16", "genre_ids": [35, 18], "id": 135647, "name": "2 Good 2 Be True", "origin_country": ["PH"], "original_language": "tl", "original_name": "2 Good 2 Be True", "overview": "Car mechanic Eloy makes a terrible first impression on Ali, who works for a real estate magnate. But both of them are hiding their true personas.", "popularity": 958.707, "poster_path": "/2Wf5ySCPcnp8lRhbSD7jt0YLz5A.jpg", "vote_average": 7.5, "vote_count": 144 },
        { "backdrop_path": "/fMvRiykSZrb5KCQnHxe3dNN5XKX.jpg", "first_air_date": "2022-06-27", "genre_ids": [18], "id": 194619, "name": "A Family Affair", "origin_country": ["PH"], "original_language": "tl", "original_name": "A Family Affair", "overview": "An inheritance from the late matriarch of the Estrellas intertwines the life of Cherry Red with Dave, Paco, Seb, and Drew. Amid the romance that arose between her and two of the four brothers, Cherry's past unravels and exposes deeply buried secrets.", "popularity": 886.87, "poster_path": "/gkap4pWN722E0UK9WNL2vjGnAtw.jpg", "vote_average": 5, "vote_count": 2 },
        { "backdrop_path": "/1UCGE1Dl7iClKIbDMcGWiHKVWCU.jpg", "first_air_date": "2022-05-30", "genre_ids": [35, 10759, 10766], "id": 197189, "name": "Cara e Coragem", "origin_country": ["BR"], "original_language": "pt", "original_name": "Cara e Coragem", "overview": "", "popularity": 1329.497, "poster_path": "/8CXbCCGiJxi4AXPBQ1QPrehMIGG.jpg", "vote_average": 5.5, "vote_count": 17 },
        { "backdrop_path": "/hNwopoqRDazw1uPHY2jSNmV2gS2.jpg", "first_air_date": "2005-06-06", "genre_ids": [10763, 10764, 99], "id": 203599, "name": "Scoop", "origin_country": [], "original_language": "cn", "original_name": "東張西望", "overview": "Scoop is a comprehensive information programme of Television Broadcasts Limited.\n\nThe content of the program is mainly based on entertainment news and personal follow-up of the artists, and will also be interspersed with the latest trends of TVB dramas and artists. Some entertainment news content clips will be rebroadcast on the next day's \"Entertainment Live\".\n\nThis program will be broadcast on Jade Channel from 19:30-20:00 (Hong Kong time) from June 6, 2005, and will be broadcast every day from March 3, 2019, and will be broadcast on myTV (later myTV SUPER) to provide \"Program Review\".", "popularity": 1299.6, "poster_path": "/qo6y0XvSBlKM3XCbYVdcR3a6qyQ.jpg", "vote_average": 7.6, "vote_count": 5 },
        { "backdrop_path": "/jW61BMd1ZVWPXI7Ts4iC2BTx8Qj.jpg", "first_air_date": "2022-04-11", "genre_ids": [18], "id": 196572, "name": "The Secret House", "origin_country": ["KR"], "original_language": "ko", "original_name": "비밀의 집", "overview": "A story about quitting being a good boy and chasing evil to the end for the sake of the mother and sister who sacrificed for themselves.\n\nA revenge play in which a dirt spoon lawyer chasing the traces of his missing mother walks into the secret surrounding him to fight the world.", "popularity": 849.496, "poster_path": "/wNN9hJDV45BF2PiJQQVwBCiqLIl.jpg", "vote_average": 6.5, "vote_count": 4 },
        { "backdrop_path": "/AnfXhKJwb9rBa8cvPBV54XgJxMF.jpg", "first_air_date": "2022-03-28", "genre_ids": [18, 10766], "id": 158415, "name": "Pantanal", "origin_country": ["BR"], "original_language": "pt", "original_name": "Pantanal", "overview": "After the mysterious disappearance of his father, Joventino, the cowboy José Leôncio becomes a wealthy farm owner in Pantanal. Over twenty years have passed and, bitter-hearted because of his father vanishing and the escape of his wife to Rio de Janeiro with his baby, José Leôncio has the chance to make amends with the boy, now a young man raised in the big city with very different values and habits than his own.", "popularity": 1407.274, "poster_path": "/4Ru1BwcAKWtpM345dWe8YgHf35V.jpg", "vote_average": 5.5, "vote_count": 39 },
        { "backdrop_path": "/eub9xDaIfNwvg0oEv5tvkAlFqrO.jpg", "first_air_date": "2019-07-25", "genre_ids": [10765, 10759], "id": 76479, "name": "The Boys", "origin_country": ["US"], "original_language": "en", "original_name": "The Boys", "overview": "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.", "popularity": 1214.193, "poster_path": "/stTEycfG9928HYGEISBFaG1ngjM.jpg", "vote_average": 8.5, "vote_count": 6999 },
        { "backdrop_path": "/vNfuoO1JU4cfE4aJjLib2LsKYRb.jpg", "first_air_date": "2021-07-12", "genre_ids": [10764], "id": 124428, "name": "B&B Vol Liefde", "origin_country": ["NL"], "original_language": "nl", "original_name": "B&B Vol Liefde", "overview": "", "popularity": 742.238, "poster_path": "/oW1TpjHFYCoCMAwE3ZmrlhEVAT5.jpg", "vote_average": 7, "vote_count": 1 },
        { "backdrop_path": "/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg", "first_air_date": "2013-09-12", "genre_ids": [18, 80], "id": 60574, "name": "Peaky Blinders", "origin_country": ["GB"], "original_language": "en", "original_name": "Peaky Blinders", "overview": "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.", "popularity": 1274.819, "poster_path": "/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg", "vote_average": 8.6, "vote_count": 7080 },
        { "backdrop_path": "/ry9SsBPOShH7eEL2dJc1coCBh8X.jpg", "first_air_date": "2022-03-07", "genre_ids": [35, 18], "id": 157936, "name": "For You", "origin_country": ["PT"], "original_language": "pt", "original_name": "Por Ti", "overview": "In the parish of Rio Meandro, two villages are at war over the construction of a dam that will submerge one of them: either Aldeia Velha or Aldeia Nova.", "popularity": 665.764, "poster_path": "/7GmlOYoR2GNiBRFs47azHIcqncR.jpg", "vote_average": 4.5, "vote_count": 6 },
        { "backdrop_path": "/zraW0rB868TzI4etGaIQYq9pw40.jpg", "first_air_date": "2019-06-09", "genre_ids": [18, 10751], "id": 90155, "name": "Growing Pain", "origin_country": ["CN"], "original_language": "zh", "original_name": "少年派", "overview": "", "popularity": 649.557, "poster_path": "/ypBz6o7pxrrVTZU4jxo6FdUFd3S.jpg", "vote_average": 3, "vote_count": 3 },
        { "backdrop_path": "/aZ4mBxYHrKHFu9QpUmpVDIOoWAb.jpg", "first_air_date": "2022-07-07", "genre_ids": [18, 80], "id": 155537, "name": "Black Bird", "origin_country": ["US"], "original_language": "en", "original_name": "Black Bird", "overview": "As Jimmy Keene begins a 10-year prison sentence, he gets an incredible offer: If he can elicit a confession from suspected killer Larry Hall, Jimmy will be freed. Completing this mission becomes the challenge of a lifetime.", "popularity": 960.984, "poster_path": "/79M2yNSmkh4CCMrWNV6b2xvIeNn.jpg", "vote_average": 8.2, "vote_count": 67 },
        { "backdrop_path": "/6KyJeOW7vTW0czdR0S6wzXAcfmw.jpg", "first_air_date": "2022-08-05", "genre_ids": [10765, 18], "id": 90802, "name": "The Sandman", "origin_country": ["US"], "original_language": "en", "original_name": "The Sandman", "overview": "After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.", "popularity": 1310.946, "poster_path": "/q54qEgagGOYCq5D1903eBVMNkbo.jpg", "vote_average": 8.1, "vote_count": 253 },
        { "backdrop_path": "/vAMnMp84ASHuiHM6YxNa3esG1o9.jpg", "first_air_date": "2020-08-17", "genre_ids": [], "id": 205401, "name": "Ik Weet Er Alles Van! (incl) VIPS", "origin_country": ["NL"], "original_language": "nl", "original_name": "Ik Weet Er Alles Van! (incl) VIPS", "overview": "", "popularity": 548.53, "poster_path": "/1UWnPL8nhyc6enkTjfJKM5Fcn0x.jpg", "vote_average": 4.5, "vote_count": 2 },
        { "backdrop_path": "/xA3Bh5VjiarQLbYH9xzpxiN1IMU.jpg", "first_air_date": "2016-01-25", "genre_ids": [80, 10765], "id": 63174, "name": "Lucifer", "origin_country": ["US"], "original_language": "en", "original_name": "Lucifer", "overview": "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.", "popularity": 874.802, "poster_path": "/ekZobS8isE6mA53RAiGDG93hBxL.jpg", "vote_average": 8.5, "vote_count": 12207 },
        { "backdrop_path": null, "first_air_date": "2022-05-30", "genre_ids": [35, 10765], "id": 152296, "name": "Love in 40 Days", "origin_country": ["PH"], "original_language": "tl", "original_name": "Love in 40 Days", "overview": "After getting involved in a fatal car crash, a competitive career woman arrives in an uncanny purgatory. While settling her unfinished businesses as a lingering spirit, she meets and finds her soulmate in a rebellious scion with a third eye.", "popularity": 507.557, "poster_path": "/7cdnr3Bu728ukVBDMcOZ8zLrwOt.jpg", "vote_average": 3.1, "vote_count": 4 },
        { "backdrop_path": "/7J5d7K4JBDZ4IDODNX3THLggtM5.jpg", "first_air_date": "2005-03-27", "genre_ids": [18], "id": 1416, "name": "Grey's Anatomy", "origin_country": ["US"], "original_language": "en", "original_name": "Grey's Anatomy", "overview": "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.", "popularity": 791.28, "poster_path": "/zPIug5giU8oug6Xes5K1sTfQJxY.jpg", "vote_average": 8.3, "vote_count": 8255 }
      ]
    );
  }, [])

  return (
    <div className="flex flex-wrap -mb-4">
      {!loading && movies?.length ? movies.map((movie, index) => <Movie key={movie?.id ?? index} movie={movie} />) : <h2>Loading...</h2>}
    </div>
  )
}

export default Movies
